### ISSUE TITLE
Can't install package

### ISSUE THREAD

**Issue by Naoray** [m1so/LeagueWrap#1]
![image](https://user-images.githubusercontent.com/10154100/28704642-fe757e9a-736b-11e7-8023-23149b4f59f5.png)

The package `php-http/client-implementation` does not exist. Could u resolve this?

Thanks,
:) Naoray

**Comment by m1so** [comment]
`php-http/client-implementation` is a virtual package, you will need to use a [specific client](http://docs.php-http.org/en/latest/clients.html) from the [php-http project](http://docs.php-http.org/en/latest/httplug/users.html). For example using Guzzle along with LeagueWrap would look like:

```bash
composer require php-http/guzzle6-adapter php-http/message guzzlehttp/psr7 m1so/leaguewrap
```

**Comment by Naoray** [comment]
Oh, sorry my mistake!!
